#!/bin/bash

BUILD_TYPE=Release # Release, Debug
BUILD_TARGET=Linux
BUILD_PREFIX=$HOME/tmp
CONFIGURE=1
VERBOSE_MAKEFILE=0
BUILD_CURL=1
BUILD_FTL=1
BUILD_SEAL=1
BUILD_CODETIPS=1
BUILD_VIDE=1
BUILD_PTE=1
BUILD_PACU=1
EMBED_SEAL=1
TEST_RUN=0
TEST_CMD=""
TEST_PARAM=""
BUNDLE=1
BUNDLE_ONLY=0
BUNDLE_VERSION=1.2.4
AUTOINCREMENT_BUILD_NUMBER=1
IMAGE_NAME=Pacu-$BUNDLE_VERSION
MAKEFLAGS=-j2
SOURCE_PREFIX=$PWD/..
CURL_PACKAGE=$PWD/../curl-7.19.5.tar.bz2
